### ISSUE TITLE
Lookup address symbol in query mode gives wrong error

### ISSUE THREAD

**Issue by claj** [Convex-Dev/convex.cljc#10]
Setup: One account, #6685 has run the transactional expression 

`(def x "Joe")`

Another account, #6686, runs - in QUERY mode:

```
(lookup #6685 'x)

Error (COMPILE)
COMPILE: lookup requires a Symbol as last argument
Trace
Compiling:(lookup #6685 (quote x))

```
When running in transaction mode the right value ("Joe") is returned.

It is confusing that the error message complains about a well formed expression but in the wrong "execution mode".

**Comment by mikera** [comment]
Thanks for the report - is this on the Sandbox? It might be a Sandbox parsing issue.

The lookup form should be something like:

```clojure
(lookup *address* x) ;; note the symbol does not need to be quoted
```

From my quick tests, this works in both Query and Transaction mode.

**Comment by claj** [comment]
Yes, now it worked for me as well. Sorry!

**Comment by mikera** [comment]
Awesome, glad problem solved!
